# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/listasdb
spring.datasource.username=usuario 
spring.datasource.password=contraseña
# El usuario y contraseña hay que cambiarlos y meterlos en una variable de entorno

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del WebSocket
server.port=8081
